WIP: Modernize?
capaj/set-tz pull request #10
Opened 2021-02-14 01:30 UTC by movermeyer

[Disclaimer: I don't really know what I'm doing].

I'm just playing around

2021-02-14 02:10 UTC, movermeyer commented on tests/set-tz.spec.js
> +    )
Ref: https://github.com/capaj/set-tz/issues/7

2022-02-14 14:22 UTC, movermeyer commented
cc @capaj

2022-02-14 14:34 UTC, capaj commented on .github/workflows/ci.yml
> +        uses: GabrielBB/xvfb-action@v1.0
this GH action should not be needed

2022-02-14 14:39 UTC, capaj requested changes
thanks for that CI yaml, just revert those imports please and also revert utc.js file

2022-02-14 14:39 UTC, capaj commented on tests/set-tz-iana.spec.js
> -import test from 'ava'
please keep ES6 imports

2022-02-14 18:06 UTC, movermeyer commented
@capaj, Unfortunately, it's been a year since I opened this PR, so I've forgotten all of the context I had at the time.

I won't be able to bring this PR back into a good state. Sorry. Feel free to use it for inspiration for another PR and/or close this PR.

2022-02-14 18:06 UTC, movermeyer commented on tests/set-tz-iana.spec.js
> -import test from 'ava'
FWIW, `npm test` fails then:

```
➜  set-tz git:(e342209) ✗ npm test

> set-tz@0.2.0 test
> ava tests -s


  Uncaught exception in tests/set-tz-iana.spec.js

  SyntaxError: Cannot use import statement outside a module

  ✖ tests/set-tz-iana.spec.js exited with a non-zero exit code: 1
```

2022-02-14 18:17 UTC, capaj commented on tests/set-tz-iana.spec.js
> -import test from 'ava'
I think ava stopped supporting ES6 syntax out of the box. We need to add a config for it.

2023-10-02 17:07 UTC, closed without merging